Repository hmcts/probate-caveats-frontend, pull requests merged in 2019-10, with the labels that each got.

#159 PRO-5862: Add request body sanitizer
  app.js
  app/middleware/sanitizeRequestBody.js
  package.json
  test/component/applicant/testApplicantName.js
  test/component/deceased/testName.js
  test/component/deceased/testOtherNames.js
  test/unit/testSanatizeRequestBody.js
  yarn.lock
Labels: ns:probate-caveats-fe-pr-159

#162 PRO-6377: Fix webchat and remove jQuery
  Jenkinsfile_CNP
  app.js
  app/assets/javascripts/jquery-1.11.3.js
  app/views/includes/scripts.html
Labels: ns:probate-caveats-fe-pr-162

#167 PRO-6428: Added Enable Tracking
  app/views/includes/scripts.html
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:probate-caveats-fe-pr-167

#169 PRO-5061: Turn off autocomplete
  app/steps/ui/applicant/address/template.html
  app/steps/ui/deceased/address/template.html
  app/views/includes/two_thirds_form.html
  app/views/widgets/addresslookup.html
Labels: ns:probate-caveats-fe-pr-169

#172 Demo merge to master
  app/components/pdf-services.js
  app/components/services.js
Labels: ns:probate-caveats-fe-pr-172
