Repository hmcts/probate-caveats-frontend, pull requests merged in 2019-03, with the labels that each got.

#32 PRO-4152 Enable calls to orchestration service
  Jenkinsfile_CNP
  app/components/FormatUrl.js
  app/components/security.js
  app/components/services.js
  app/components/submit-data.js
  app/config.js
  app/resources/en/translation/stoppage.json
  app/steps/ui/summary/index.js
  app/utils/FormatCcdCaseId.js
  charts/probate-caveats-fe/values.template.yaml
  docker/docker-compose.yml
  infrastructure/main.tf
  infrastructure/variables.tf
  package.json
  test/component/summary/testSummary.js
  test/data/full-caveat-form.json
  test/data/unit/fullcaveatform.json
  test/data/unit/minimalcaveatform.json
  test/service-stubs/idam.js
  test/service-stubs/orchestration.js
  test/service-stubs/s2s.js
  test/unit/testFormatUrl.js
  test/unit/testPdf-services.js
  test/unit/testSubmitData.js
  test/util/TestWrapper.js
  yarn.lock
Labels: ns:probate-caveats-fe-pr-32

#37 Pro 4136 add basic payments screens to caveat journey
  app/components/api-utils.js
  app/components/payment-data.js
  app/components/security.js
  app/components/services.js
  app/components/submit-data.js
  app/config.js
  app/core/runners/RedirectRunner.js
  app/journeys/probate-caveats.js
  app/resources/en/translation/payment/breakdown.json
  app/resources/en/translation/payment/status.json
  app/steps/ui/payment/breakdown/index.js
  app/steps/ui/payment/breakdown/template.html
  app/steps/ui/payment/status/index.js
  app/steps/ui/payment/status/template.html
  app/steps/ui/summary/index.js
  charts/probate-caveats-fe/values.template.yaml
  test/accessibility/a11yTest.js
  test/component/payment/testPaymentBreakdown.js
  test/component/payment/testPaymentStatus.js
  test/component/summary/testSummary.js
  test/data/unit/fullcaveatform.json
  test/data/unit/minimalcaveatform.json
  test/end-to-end/pages/payment/breakdown.js
  test/end-to-end/pages/steps.js
  test/end-to-end/paths/standardExecutionPath.js
  test/service-stubs/orchestration.js
  test/unit/testPdf-services.js
  test/unit/testSecurity.js
  test/unit/testSubmitData.js
Labels: ns:probate-caveats-fe-pr-37

#38 Update UIStepRunner to pass hostname on handlepost
  app/core/runners/UIStepRunner.js
  charts/probate-caveats-fe/values.template.yaml
Labels: ns:probate-caveats-fe-pr-38

#39 Pro 4933 Revised payment flow
  app/components/FormatUrl.js
  app/components/api-utils.js
  app/components/pdf-services.js
  app/components/security.js
  app/components/services.js
  app/config.js
  app/middleware/downloadCheckAnswersPdf.js
  app/resources/en/translation/payment/breakdown.json
  app/resources/en/translation/payment/status.json
  app/routes.js
  app/steps/ui/payment/breakdown/index.js
  app/steps/ui/payment/status/index.js
  app/steps/ui/payment/status/template.html
  charts/probate-caveats-fe/values.template.yaml
  test/component/payment/testPaymentStatus.js
  test/component/testApi-Utils.js
  test/unit/testDownloadCheckAnswersPdf.js
  test/unit/testPaymentStatus.js
  test/unit/testSecurity.js
  test/util/TestWrapper.js
Labels: ns:probate-caveats-fe-pr-39

#46 PRO-4933: change https to http for orchestration service
  infrastructure/aat.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
Labels: ns:probate-caveats-fe-pr-46

#47 Pro 5001 change caveat submission identifier
  app/components/pdf-services.js
  app/components/services.js
  app/components/submit-data.js
  app/core/runners/RedirectRunner.js
  app/routes.js
  package.json
  test/data/unit/fullcaveatform.json
  test/data/unit/minimalcaveatform.json
  test/unit/testSubmitData.js
Labels: ns:probate-caveats-fe-pr-47

#51 PRO 4992 Stop duplicate caveat submissions on double click
  Dockerfile
  app/components/security.js
  app/middleware/lockPaymentAttempt.js
  app/routes.js
  app/steps/ui/payment/breakdown/index.js
  app/steps/ui/payment/status/index.js
  test/component/payment/testPaymentBreakdown.js
  test/component/payment/testPaymentStatus.js
  test/unit/testLockPaymentAttempt.js
  test/unit/testPaymentBreakdown.js
Labels: ns:probate-caveats-fe-pr-51

#52 unbreaking prod build
  Jenkinsfile_CNP
Labels: ns:probate-caveats-fe-pr-52

#53 Adding vars to prod.tfvars
  infrastructure/prod.tfvars
Labels: ns:probate-caveats-fe-pr-53

#57 chart to sidam
  charts/probate-caveats-fe/values.template.yaml
Labels: ns:probate-caveats-fe-pr-57

#54 PRO-4984: ensure that alias names are displyed and reset correctly
  app/steps/ui/deceased/alias/index.js
Labels: ns:probate-caveats-fe-pr-54

#50 PRO-5027: Amend copy on Start Eligibility page
  app/resources/en/translation/startpage.json
Labels: ns:probate-caveats-fe-pr-50

#55 Pro 5057 set secure flag on cookie
  app.js
Labels: ns:probate-caveats-fe-pr-55
