Repository hmcts/probate-caveats-frontend, pull requests merged in 2019-07, with the labels that each got.

#130 PRO-5546: Caveat payment callback
  app/components/services.js
  app/config.js
Labels: ns:probate-caveats-fe-pr-130

#137 PRO-5747: update cheerio text command
  app/utils/CheckAnswersSummaryJSONObjectBuilder.js
  test/unit/testCheckAnswersSummaryJSONObjectBuilder.js
Labels: ns:probate-caveats-fe-pr-137

#141 PRO-5831: Fix bug with addresses containing single quotes
  app/views/widgets/addresslookup.html
Labels: ns:probate-caveats-fe-pr-141

#139 PRO-5721: Add paragraph to Start Page
  app/config.js
  app/resources/en/translation/common.json
  app/resources/en/translation/contact.json
  app/resources/en/translation/cookies.json
  app/resources/en/translation/privacy.json
  app/resources/en/translation/shutterpage.json
  app/resources/en/translation/startpage.json
  app/resources/en/translation/terms.json
  app/resources/en/translation/thankyou.json
  app/steps/ui/startpage/template.html
  app/views/includes/footer_links.html
  app/views/includes/phase_banner_beta.html
  package.json
  test/component/applicant/testAddress.js
  test/component/contact/index.js
  test/component/cookies/index.js
  test/component/deceased/testAddress.js
  test/component/deceased/testAlias.js
  test/component/deceased/testOtherNames.js
  test/component/privacy/index.js
  test/component/startpage/testStartPage.js
  test/component/summary/testSummary.js
  test/component/terms/index.js
  test/component/testShutterPage.js
Labels: ns:probate-caveats-fe-pr-139

#142 PRO-5835: Updated to handle quotes in address using caveat postcode lookup
  app/components/string-utils.js
  test/unit/testStringUtils.js
Labels: ns:probate-caveats-fe-pr-142
