Repository hmcts/probate-caveats-frontend, pull requests merged in 2019-04, with the labels that each got.

#60 PRO-5053: Add 2 paragraphs to Start Page
  app/assets/sass/application-common.scss
  app/resources/en/translation/startpage.json
  app/steps/ui/startpage/template.html
Labels: ns:probate-caveats-fe-pr-60

#61 Adding SIDAM curl
  Jenkinsfile_CNP
Labels: ns:probate-caveats-fe-pr-61

#68 PRO-5106: Change email address on AD block
  app/config.js
  app/resources/en/translation/common.json
  app/views/includes/help_details.html
  test/component/common/testHelpBlockContent.js
Labels: ns:probate-caveats-fe-pr-68

#67 PRO-5099: Correct minor sonar issues
  .gitignore
  app/core/steps/Step.js
  app/steps/ui/startpage/template.html
  app/steps/ui/summary/template.html
  app/views/widgets/checkanswer.html
  sonar-project.properties
Labels: ns:probate-caveats-fe-pr-67

#69 PRO-5007: New improved logging
  app/components/api-utils.js
  app/components/logger.js
  app/components/pdf-services.js
  app/components/security.js
  app/components/services.js
  app/routes.js
  app/steps/ui/payment/breakdown/index.js
  app/steps/ui/payment/status/index.js
  test/unit/testSecurity.js
Labels: ns:probate-caveats-fe-pr-69

#71 Updated E2E tests and catch block for Async
  test/end-to-end/helpers/PuppeteerHelper.js
  test/end-to-end/paths/standardExecutionPath.js
Labels: ns:probate-caveats-fe-pr-71

#72 PRO-5121: Change dl, div and dt/dd to table, tr and th/td
  app/steps/ui/summary/includes/about-you.njk
  app/steps/ui/summary/includes/deceased.njk
  app/steps/ui/summary/template.html
  app/views/widgets/checkanswer.html
  test/unit/testCheckAnswersSummaryJSONObjectBuilder.js
Labels: ns:probate-caveats-fe-pr-72

#73 PRO-5142: change google tracker id and remove redundant config
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  app/config.js
  charts/probate-caveats-fe/values.aat.template.yaml
  charts/probate-caveats-fe/values.template.yaml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
  kubernetes/.lint.yml
  kubernetes/README.md
  kubernetes/config.aat.yaml
  kubernetes/deployment.template.yaml
  test/config.js
Labels: ns:probate-caveats-fe-pr-73

#74 PRO-5063: add anti-caching directives and increase smoke test timeout
  app.js
  package.json
Labels: ns:probate-caveats-fe-pr-74

#78 PRO-5151: Shutter FT
  app/config.js
  app/resources/en/translation/shutterpage.json
  app/routes.js
  app/services/FeatureToggle.js
  app/shutter.js
  app/steps/ui/shutterpage/index.js
  app/steps/ui/shutterpage/template.html
  app/utils/FeatureToggle.js
  charts/probate-caveats-fe/requirements.yaml
  charts/probate-caveats-fe/values.template.yaml
  package.json
  test/accessibility/a11yTest.js
  test/component/testShutterPage.js
  test/service-stubs/persistence.js
  test/unit/testFeatureToggle.js
  test/unit/testFeatureToggleService.js
  test/unit/testShutterPage.js
  yarn.lock
Labels: ns:probate-caveats-fe-pr-78

#80 unbreak pipeline
  Jenkinsfile_CNP
Labels: ns:probate-caveats-fe-pr-80

#81 Update config.js
  app/config.js
Labels: ns:probate-caveats-fe-pr-81

#83 Demo
  app.js
  app/config.js
  app/core/runners/ActionStepRunner.js
  app/core/runners/RedirectRunner.js
  app/core/runners/UIStepRunner.js
  app/routes.js
  app/steps/action/addAlias/index.js
  app/steps/action/addressLookup/index.js
  app/steps/action/removeAlias/index.js
  app/steps/ui/applicant/address/index.js
  app/steps/ui/applicant/address/template.html
  app/steps/ui/applicant/email/index.js
  app/steps/ui/applicant/name/index.js
  app/steps/ui/deceased/address/index.js
  app/steps/ui/deceased/address/template.html
  app/steps/ui/deceased/alias/index.js
  app/steps/ui/deceased/dob/index.js
  app/steps/ui/deceased/dobknown/index.js
  app/steps/ui/deceased/dod/index.js
  app/steps/ui/deceased/name/index.js
  app/steps/ui/deceased/othernames/index.js
  app/steps/ui/deceased/othernames/template.html
  app/steps/ui/payment/breakdown/index.js
  app/steps/ui/payment/status/index.js
  app/steps/ui/startpage/template.html
  app/steps/ui/summary/includes/about-you.njk
  app/steps/ui/summary/includes/deceased.njk
  app/steps/ui/summary/index.js
  app/steps/ui/summary/template.html
  app/views/includes/footer_links.html
  app/views/includes/propositional_navigation.html
  app/views/includes/two_thirds_form.html
  app/views/widgets/addresslookup.html
  app/views/widgets/checkanswer.html
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  test/accessibility/a11yTest.js
  test/component/applicant/testAddress.js
  test/component/applicant/testApplicantEmail.js
  test/component/applicant/testApplicantName.js
  test/component/contact/index.js
  test/component/cookies/index.js
  test/component/deceased/testAddress.js
  test/component/deceased/testAlias.js
  test/component/deceased/testDoB.js
  test/component/deceased/testDoD.js
  test/component/deceased/testDoDKnown.js
  test/component/deceased/testName.js
  test/component/deceased/testOtherNames.js
  test/component/payment/testPaymentBreakdown.js
  test/component/payment/testPaymentStatus.js
  test/component/startpage/testStartPage.js
  test/component/summary/testAboutYouSection.js
  test/component/summary/testDeceasedSection.js
  test/component/summary/testSummary.js
  test/component/thankyou/testThankYouPage.js
  test/util/TestWrapper.js
Labels: ns:probate-caveats-fe-pr-83

#85 E2e test
  Jenkinsfile_CNP
  app/config.js
  app/routes.js
  charts/probate-caveats-fe/values.template.yaml
  infrastructure/main.tf
  test/config.js
  test/end-to-end/helpers/TestConfigurator.js
  test/end-to-end/pages/applicant/name.js
  test/end-to-end/pages/deceased/dob.js
  test/end-to-end/pages/deceased/dod.js
  test/end-to-end/pages/payment/paymentbreakdown.js
  test/end-to-end/pages/payment/paymentstatus.js
  test/end-to-end/pages/startpage/startpage.js
  test/end-to-end/pages/thankyou/thankyou.js
  test/end-to-end/paths/standardExecutionPath.js
  test/unit/testApplicantAddress.js
  test/unit/testApplicantEmail.js
  test/unit/testApplicantName.js
  test/unit/testDeceasedAddress.js
  test/unit/testDeceasedAlias.js
  test/unit/testDeceasedDob.js
  test/unit/testDeceasedDobKnown.js
  test/unit/testDeceasedDod.js
  test/unit/testDeceasedName.js
  test/unit/testOtherNames.js
  test/unit/testPaymentBreakdown.js
  test/unit/testPaymentStatus.js
  test/unit/testSummary.js
Labels: ns:probate-caveats-fe-pr-85

#87 add sidam helm chart for whitelisting
  Jenkinsfile_CNP
  charts/probate-caveats-fe/Chart.yaml
  charts/probate-caveats-fe/requirements.yaml
  charts/probate-caveats-fe/values.template.yaml
Labels: ns:probate-caveats-fe-pr-87

#88 PRO-5187: additional logging
  app/components/security.js
Labels: ns:probate-caveats-fe-pr-88

#92 PRO-5187: remove additional logging for discovering hostname
  app/components/security.js
Labels: ns:probate-caveats-fe-pr-92

#79 Pro 4946 hardening caveat flow
  app/config.js
  app/routes.js
  app/services/FeatureToggle.js
  package.json
  test/accessibility/a11yTest.js
  test/accessibility/app.js
  test/component/applicant/testAddress.js
  test/component/applicant/testApplicantEmail.js
  test/component/common/testHelpBlockContent.js
  test/component/deceased/testAddress.js
  test/component/deceased/testAlias.js
  test/component/deceased/testDoB.js
  test/component/deceased/testDoD.js
  test/component/deceased/testDoDKnown.js
  test/component/deceased/testName.js
  test/component/deceased/testOtherNames.js
  test/component/payment/testPaymentBreakdown.js
  test/component/payment/testPaymentStatus.js
  test/component/summary/testAboutYouSection.js
  test/component/summary/testDeceasedSection.js
  test/component/summary/testSummary.js
  test/component/testStartPageRedirects.js
  test/component/testThankYouRedirects.js
  test/component/thankyou/testThankYouPage.js
  test/config.js
  test/data/deceased.json
  test/unit/testFeatureToggle.js
  yarn.lock
Labels: ns:probate-caveats-fe-pr-79

#93 Fix health and set return path env var
  app.js
  app/components/services.js
  app/config.js
  charts/probate-caveats-fe/values.template.yaml
Labels: ns:probate-caveats-fe-pr-93

#98 PRO-4964: Wrap whitelist pages with app_base_path
  app/config.js
Labels: ns:probate-caveats-fe-pr-98

#89 use internal url for idam callback
  app/components/security.js
  app/config.js
  charts/probate-caveats-fe/values.aat.template.yaml
  charts/probate-caveats-fe/values.template.yaml
  infrastructure/main.tf
Labels: ns:probate-caveats-fe-pr-89

#107 Add /public to the whitelisted paths for css and js
  Jenkinsfile_CNP
  app.js
  app/config.js
  app/core/runners/UIStepRunner.js
  app/views/includes/head.html
  app/views/includes/scripts.html
  package.json
  yarn.lock
Labels: ns:probate-caveats-fe-pr-107

#108 Simplify healthcheck
  test/smoke/healthcheck.js
Labels: ns:probate-caveats-fe-pr-108

#109 Re-enable deploying to Prod
  Jenkinsfile_CNP
Labels: ns:probate-caveats-fe-pr-109
