Repository hmcts/probate-caveats-frontend, pull requests merged in 2020-02, with the labels that each got.

#198 [DO NOT MERGE] WLA-296: Fix link to Bilingual question
  app/steps/ui/summary/includes/about-you.njk
  app/steps/ui/summary/index.js
Labels: ns:probate, rel:probate-caveats-fe-pr-198

#199 Pass empty flag is language is EN
  app/components/payment-data.js
Labels: ns:probate, rel:probate-caveats-fe-pr-199

#203 PRO-1234: unbreak pipeline
  Jenkinsfile_CNP
Labels: ns:probate, rel:probate-caveats-fe-pr-203

#204 Move Language question
  app/core/steps/ValidationStep.js
  app/journeys/probate-caveats.js
  app/steps/ui/applicant/address/index.js
  app/steps/ui/applicant/email/index.js
  app/steps/ui/applicant/name/index.js
  app/steps/ui/deceased/address/index.js
  app/steps/ui/deceased/alias/index.js
  app/steps/ui/deceased/dob/index.js
  app/steps/ui/deceased/dobknown/index.js
  app/steps/ui/deceased/dod/index.js
  app/steps/ui/deceased/name/index.js
  app/steps/ui/deceased/othernames/index.js
  app/steps/ui/payment/breakdown/index.js
  app/steps/ui/payment/status/index.js
  app/steps/ui/startapply/index.js
  app/steps/ui/startapply/template.html
  app/steps/ui/summary/includes/about-you.njk
  app/steps/ui/summary/index.js
  test/component/deceased/testAddress.js
  test/unit/testApplicantAddress.js
  test/unit/testApplicantEmail.js
  test/unit/testApplicantName.js
  test/unit/testDeceasedAddress.js
  test/unit/testDeceasedAlias.js
  test/unit/testDeceasedDobKnown.js
  test/unit/testDeceasedName.js
  test/unit/testOtherNames.js
  test/unit/testPaymentBreakdown.js
  test/unit/testPaymentStatus.js
  test/unit/testSummary.js
Labels: ns:probate, rel:probate-caveats-fe-pr-204

#205 Pro 7062 update fees code
  app/config.js
  app/utils/FeesLookup.js
Labels: ns:probate, rel:probate-caveats-fe-pr-205
