Repository hmcts/probate-caveats-frontend, pull requests merged in 2020-11, with the labels that each got.

#276 Pro 5837 persist deceased alias pa caveat
  app/components/submit-data.js
  test/data/full-caveat-form.json
  test/data/unit/fullcaveatform.json
  test/data/unit/minimalcaveatform.json
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-276

#294 Bug/pro 7198 non descriptive links
  app/resources/cy/translation/startapply.json
  app/resources/en/translation/startapply.json
  app/steps/ui/startapply/template.html
  config/default.yaml
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-294

#284 Bug/pro 7209 address line 1 accessibility
  app/resources/cy/translation/applicant/address.json
  app/resources/en/translation/applicant/address.json
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-284

#290 Bug/pro 7191 accessibility description for summary links
  app/resources/cy/translation/applicant/address.json
  app/resources/cy/translation/applicant/email.json
  app/resources/cy/translation/applicant/name.json
  app/resources/cy/translation/deceased/address.json
  app/resources/cy/translation/deceased/alias.json
  app/resources/cy/translation/deceased/dob.json
  app/resources/cy/translation/deceased/dobknown.json
  app/resources/cy/translation/deceased/dod.json
  app/resources/cy/translation/deceased/name.json
  app/resources/cy/translation/deceased/othernames.json
  app/resources/cy/translation/language.json
  app/resources/cy/translation/summary.json
  app/resources/en/translation/applicant/address.json
  app/resources/en/translation/applicant/email.json
  app/resources/en/translation/applicant/name.json
  app/resources/en/translation/deceased/address.json
  app/resources/en/translation/deceased/alias.json
  app/resources/en/translation/deceased/dob.json
  app/resources/en/translation/deceased/dobknown.json
  app/resources/en/translation/deceased/dod.json
  app/resources/en/translation/deceased/name.json
  app/resources/en/translation/deceased/othernames.json
  app/resources/en/translation/language.json
  app/resources/en/translation/summary.json
  app/steps/ui/summary/includes/about-you.njk
  app/steps/ui/summary/includes/deceased.njk
  app/views/widgets/checkanswer.njk
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-290

#289 Pro 7190 duplicate page titles
  app/resources/cy/translation/deceased/address.json
  app/resources/cy/translation/deceased/dobknown.json
  app/resources/cy/translation/deceased/othernames.json
  app/resources/en/translation/deceased/address.json
  app/resources/en/translation/deceased/dobknown.json
  app/resources/en/translation/deceased/othernames.json
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-289

#282 remove the fieldset and legend as it's only has 1 input as they are n…
  app/steps/ui/applicant/email/template.html
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-282
