Repository hmcts/probate-caveats-frontend, pull requests merged in 2020-10, with the labels that each got.

#308 update terraform
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-308

#309 remove pcq health check and pcq health check tests
  app/healthcheck.js
  test/unit/utils/testHealthcheck.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-309

#313 PRO-728: remove - from the uuid for google analytics
  app.js
  app/core/runners/RedirectRunner.js
  app/middleware/completeEqualityTask.js
  app/routes.js
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-313
