Repository hmcts/probate-caveats-frontend, pull requests merged in 2020-09, with the labels that each got.

#303 fix for crashing app
  app/core/initSteps.js
  app/routes.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-303

#304 set up dev env
  .env
  .gitignore
  app/components/launch-darkly.js
  config/dev.yaml
  config/dev_template.yaml
  docker-compose.yml
  docker/database/Dockerfile
  docker/database/create-multiple-postgres-database.sh
  docker/docker-compose.yml
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-304

#306 DTSPB-515 env var for launch darkly
  charts/probate-caveats-fe/values.aat.template.yaml
  charts/probate-caveats-fe/values.preview.template.yaml
  config/custom-environment-variables.yaml
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-306

#307 DTSPB-607 Updated Jenkins cnp file for the nightly builds
  Jenkinsfile_nightly
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-307
