Repository hmcts/probate-caveats-frontend, pull requests merged in 2020-03, with the labels that each got.

#210 AKS Migration : Moving to node 12
  .gitkeep
  .nvmrc
  Dockerfile
  README.md
  infrastructure/main.tf
  infrastructure/variables.tf
  package.json
Labels: ns:probate, rel:probate-caveats-fe-pr-210

#211 Use node config
  Dockerfile
  app.js
  app/components/api-utils.js
  app/components/payment-data.js
  app/components/pdf-services.js
  app/components/security.js
  app/components/services.js
  app/config.js
  app/core/runners/ActionStepRunner.js
  app/core/runners/RedirectRunner.js
  app/core/steps/DateStep.js
  app/core/steps/Step.js
  app/routes.js
  app/services/FeatureToggle.js
  app/steps/action/addAlias/index.js
  app/steps/action/removeAlias/index.js
  app/utils/FeatureToggle.js
  app/utils/FormatUrl.js
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  test/accessibility/a11yTest.js
  test/component/applicant/testAddress.js
  test/component/applicant/testApplicantEmail.js
  test/component/applicant/testApplicantName.js
  test/component/deceased/testAddress.js
  test/component/deceased/testAlias.js
  test/component/deceased/testDoB.js
  test/component/deceased/testDoD.js
  test/component/deceased/testDoDKnown.js
  test/component/deceased/testName.js
  test/component/deceased/testOtherNames.js
  test/component/payment/testPaymentBreakdown.js
  test/component/payment/testPaymentStatus.js
  test/component/startpage/testStartPage.js
  test/component/static/testAccessibility.js
  test/component/static/testContactUs.js
  test/component/static/testCookies.js
  test/component/static/testPrivacyPolicy.js
  test/component/static/testTermsAndConditions.js
  test/component/summary/testAboutYouSection.js
  test/component/summary/testDeceasedSection.js
  test/component/summary/testSummary.js
  test/component/testApi-Utils.js
  test/component/testShutterPage.js
  test/component/thankyou/testThankYouPage.js
  test/service-stubs/feature-toggles.js
  test/service-stubs/orchestrator.js
  test/service-stubs/persistence.js
  test/unit/testFeatureToggleService.js
  test/util/TestWrapper.js
  yarn.lock
Labels: ns:probate, rel:probate-caveats-fe-pr-211

#212 Fixing node version as app service isn't supporting 12.14.1
  .nvmrc
  README.md
  infrastructure/variables.tf
  package.json
Labels: ns:probate, rel:probate-caveats-fe-pr-212

#214 PRO-7155: Generate CSRF Token correctly
  app.js
  config/custom-environment-variables.yaml
  config/default.yaml
Labels: ns:probate, rel:probate-caveats-fe-pr-214

#213 Clean up charts and use properties volume
  Dockerfile
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  app/setupSecrets.js
  charts/probate-caveats-fe/Chart.yaml
  charts/probate-caveats-fe/requirements.yaml
  charts/probate-caveats-fe/values.aat.template.yaml
  charts/probate-caveats-fe/values.preview.template.yaml
  charts/probate-caveats-fe/values.yaml
  config/custom-environment-variables.yaml
  config/testing.yaml
  infrastructure/main.tf
  package.json
  server.js
  test/config.js
  test/end-to-end/codecept.conf.js
  test/end-to-end/helpers/TestConfigurator.js
  test/end-to-end/pages/payment/govukconfirmpayment.js
  test/end-to-end/pages/payment/govukpayment.js
  test/smoke/healthcheck.js
  test/unit/testSetupSecrets.js
  yarn.lock
Labels: ns:probate, rel:probate-caveats-fe-pr-213

#217 fix redis password mapping
  app/setupSecrets.js
  test/unit/testSetupSecrets.js
Labels: ns:probate, rel:probate-caveats-fe-pr-217

#218 fixing port
  charts/probate-caveats-fe/Chart.yaml
  charts/probate-caveats-fe/values.preview.template.yaml
  charts/probate-caveats-fe/values.yaml
Labels: ns:probate, rel:probate-caveats-fe-pr-218

#219 fix vulnerabilities and yarn scripts
  package.json
  yarn.lock
Labels: ns:probate, rel:probate-caveats-fe-pr-219

#222 fix probate frontend secret from code
  infrastructure/main.tf
Labels: ns:probate, rel:probate-caveats-fe-pr-222

#223 Bumping node chart
  charts/probate-caveats-fe/Chart.yaml
  charts/probate-caveats-fe/requirements.yaml
Labels: ns:probate, rel:probate-caveats-fe-pr-223

#226 fix secret mapping
  app/setupSecrets.js
  test/unit/testSetupSecrets.js
Labels: ns:probate, rel:probate-caveats-fe-pr-226

#207 PRO-6972: Remove Persistence
  config/default.yaml
  test/service-stubs/persistence.js
Labels: ns:probate, rel:probate-caveats-fe-pr-207
