Repository hmcts/probate-caveats-frontend, pull requests merged in 2020-05, with the labels that each got.

#246 PRO-7201: Errors in error summary to be same as inline errors
  app/components/error.js
  app/resources/cy/translation/addAlias.json
  app/resources/cy/translation/addressLookup.json
  app/resources/cy/translation/applicant/address.json
  app/resources/cy/translation/applicant/email.json
  app/resources/cy/translation/applicant/name.json
  app/resources/cy/translation/common.json
  app/resources/cy/translation/deceased/address.json
  app/resources/cy/translation/deceased/alias.json
  app/resources/cy/translation/deceased/dob.json
  app/resources/cy/translation/deceased/dobknown.json
  app/resources/cy/translation/deceased/dod.json
  app/resources/cy/translation/deceased/name.json
  app/resources/cy/translation/deceased/othernames.json
  app/resources/cy/translation/language.json
  app/resources/cy/translation/payment/breakdown.json
  app/resources/cy/translation/removeAlias.json
  app/resources/en/translation/addAlias.json
  app/resources/en/translation/addressLookup.json
  app/resources/en/translation/applicant/address.json
  app/resources/en/translation/applicant/email.json
  app/resources/en/translation/applicant/name.json
  app/resources/en/translation/common.json
  app/resources/en/translation/deceased/address.json
  app/resources/en/translation/deceased/alias.json
  app/resources/en/translation/deceased/dob.json
  app/resources/en/translation/deceased/dobknown.json
  app/resources/en/translation/deceased/dod.json
  app/resources/en/translation/deceased/name.json
  app/resources/en/translation/deceased/othernames.json
  app/resources/en/translation/language.json
  app/resources/en/translation/payment/breakdown.json
  app/resources/en/translation/removeAlias.json
  app/steps/ui/applicant/address/template.html
  app/steps/ui/applicant/email/template.html
  app/steps/ui/applicant/name/template.html
  app/steps/ui/deceased/address/template.html
  app/steps/ui/deceased/alias/template.html
  app/steps/ui/deceased/dob/template.html
  app/steps/ui/deceased/dobknown/template.html
  app/steps/ui/deceased/dod/template.html
  app/steps/ui/deceased/name/template.html
  app/steps/ui/deceased/othernames/template.html
  app/steps/ui/language/template.html
  app/views/includes/error_summary.html
  app/views/includes/layout.html
  app/views/widgets/fielderror.html
  test/unit/testDeceasedDob.js
  test/unit/testDeceasedDod.js
  test/util/TestWrapper.js
Labels: ns:probate, rel:probate-caveats-fe-pr-246

#255 PRO-7201: Add Welsh translations
  app/resources/cy/translation/addAlias.json
  app/resources/cy/translation/applicant/address.json
  app/resources/cy/translation/applicant/email.json
  app/resources/cy/translation/applicant/name.json
  app/resources/cy/translation/deceased/address.json
  app/resources/cy/translation/deceased/dob.json
  app/resources/cy/translation/deceased/dod.json
  app/resources/cy/translation/deceased/name.json
  app/resources/cy/translation/deceased/othernames.json
  app/resources/cy/translation/removeAlias.json
Labels: ns:probate, rel:probate-caveats-fe-pr-255

#256 PRO-7373: Update webchat dependency
  package.json
  yarn.lock
Labels: ns:probate, rel:probate-caveats-fe-pr-256

#257 PRO-7373: changes to Sonar Scan
  package.json
Labels: ns:probate, rel:probate-caveats-fe-pr-257

#259 LaunchDarkly Performance Improvements
  app.js
  app/components/launch-darkly.js
  app/utils/FeatureToggle.js
  config/default.yaml
  config/test.yaml
  config/testing.yaml
  test/unit/components/testLaunchDarkly.js
  test/unit/utils/testFeatureToggle.js
Labels: ns:probate, rel:probate-caveats-fe-pr-259

#240 PCQ
  Jenkinsfile_CNP
  README.md
  app.js
  app/components/api-utils.js
  app/components/launch-darkly.js
  app/components/pdf-services.js
  app/components/security.js
  app/components/services.js
  app/components/step-utils.js
  app/components/submit-data.js
  app/core/runners/ActionStepRunner.js
  app/core/runners/OptionGetRunner.js
  app/core/runners/RedirectRunner.js
  app/featureToggles.js
  app/healthcheck.js
  app/journeys/probate-caveats.js
  app/middleware/completeEqualityTask.js
  app/middleware/downloadCheckAnswersPdf.js
  app/resources/cy/translation/equality.json
  app/resources/en/translation/equality.json
  app/routes.js
  app/steps/ui/equality/index.js
  app/steps/ui/equality/schema.json
  app/steps/ui/payment/status/index.js
  app/steps/ui/summary/index.js
  app/utils/FeatureToggle.js
  app/utils/FeesLookup.js
  app/utils/Healthcheck.js
  charts/probate-caveats-fe/Chart.yaml
  charts/probate-caveats-fe/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/test.yaml
  config/testing.yaml
  package.json
  test/accessibility/a11yTest.js
  test/component/payment/testPaymentBreakdown.js
  test/data/launchdarkly/simple_flag_data.yaml
  test/data/unit/fullcaveatform.json
  test/data/unit/minimalcaveatform.json
  test/service-stubs/equalityAndDiversityEndpoint.js
  test/service-stubs/equalityAndDiversityHealth.js
  test/service-stubs/orchestrator.js
  test/unit/components/testLaunchDarkly.js
  test/unit/components/testPdf-services.js
  test/unit/components/testSecurity.js
  test/unit/components/testStringUtils.js
  test/unit/components/testSubmitData.js
  test/unit/core/testActionStepRunner.js
  test/unit/core/testOptionGetRunner.js
  test/unit/middleware/testCompleteEqualityTask.js
  test/unit/middleware/testDownloadCheckAnswersPdf.js
  test/unit/middleware/testLockPaymentAttempt.js
  test/unit/middleware/testLookupPaymentFees.js
  test/unit/testEquality.js
  test/unit/testHealthcheck.js
  test/unit/testSummary.js
  test/unit/utils/testCheckAnswersSummaryJSONObjectBuilder.js
  test/unit/utils/testFeatureToggle.js
  test/unit/utils/testHealthcheck.js
Labels: ns:probate, rel:probate-caveats-fe-pr-240

#263 Revert "Revert "Revert "Revert "PCQ""""
  Jenkinsfile_CNP
  README.md
  app.js
  app/components/api-utils.js
  app/components/launch-darkly.js
  app/components/pdf-services.js
  app/components/security.js
  app/components/services.js
  app/components/step-utils.js
  app/components/submit-data.js
  app/core/runners/ActionStepRunner.js
  app/core/runners/OptionGetRunner.js
  app/core/runners/RedirectRunner.js
  app/featureToggles.js
  app/healthcheck.js
  app/journeys/probate-caveats.js
  app/middleware/completeEqualityTask.js
  app/middleware/downloadCheckAnswersPdf.js
  app/resources/cy/translation/equality.json
  app/resources/en/translation/equality.json
  app/routes.js
  app/steps/ui/equality/index.js
  app/steps/ui/equality/schema.json
  app/steps/ui/payment/status/index.js
  app/steps/ui/summary/index.js
  app/utils/FeatureToggle.js
  app/utils/FeesLookup.js
  app/utils/Healthcheck.js
  charts/probate-caveats-fe/Chart.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/test.yaml
  config/testing.yaml
  package.json
  test/accessibility/a11yTest.js
  test/component/payment/testPaymentBreakdown.js
  test/data/launchdarkly/simple_flag_data.yaml
  test/data/unit/fullcaveatform.json
  test/data/unit/minimalcaveatform.json
  test/service-stubs/equalityAndDiversityEndpoint.js
  test/service-stubs/equalityAndDiversityHealth.js
  test/service-stubs/orchestrator.js
  test/unit/components/testLaunchDarkly.js
  test/unit/components/testPdf-services.js
  test/unit/components/testSecurity.js
  test/unit/components/testStringUtils.js
  test/unit/components/testSubmitData.js
  test/unit/core/testActionStepRunner.js
  test/unit/core/testOptionGetRunner.js
  test/unit/middleware/testCompleteEqualityTask.js
  test/unit/middleware/testDownloadCheckAnswersPdf.js
  test/unit/middleware/testLockPaymentAttempt.js
  test/unit/middleware/testLookupPaymentFees.js
  test/unit/testEquality.js
  test/unit/testHealthcheck.js
  test/unit/testSummary.js
  test/unit/utils/testCheckAnswersSummaryJSONObjectBuilder.js
  test/unit/utils/testFeatureToggle.js
  test/unit/utils/testHealthcheck.js
Labels: ns:probate, rel:probate-caveats-fe-pr-263

#265 Remove PCQ ID if PCQ is down
  app/components/submit-data.js
  app/middleware/completeEqualityTask.js
  test/unit/middleware/testCompleteEqualityTask.js
Labels: ns:probate, rel:probate-caveats-fe-pr-265

#267 Change locale to lng for consistency with other services
  app.js
  app/resources/cy/translation/common.json
  app/resources/en/translation/common.json
Labels: ns:probate, rel:probate-caveats-fe-pr-267

#270 Check PCQ BE health
  app/middleware/completeEqualityTask.js
  app/utils/Healthcheck.js
  test/service-stubs/equalityAndDiversityHealth.js
Labels: ns:probate, rel:probate-caveats-fe-pr-270
