Repository hmcts/probate-caveats-frontend, pull requests merged in 2020-12, with the labels that each got.

#330 DTSPB-958-CavetE2E-Tests fix
  bin/run-functional-tests.sh
  config/testing.yaml
  test/end-to-end/config.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-330

#315 DTSPB-667: use probate email validation library
  app/steps/ui/applicant/email/index.js
  app/steps/ui/applicant/email/schema.json
  package.json
  test/component/applicant/testApplicantEmail.js
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-315

#331 Dtspb 972 welsh caveat e2 e
  Jenkinsfile_CNP
  config/default.yaml
  test/end-to-end/codecept.conf.js
  test/end-to-end/paths/caveat.e2e.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-331

#316 Dtspb 132 feature toggle newfee register code
  app/featureToggles.js
  app/middleware/lookupPaymentFees.js
  app/steps/ui/payment/breakdown/index.js
  app/utils/FeesLookup.js
  charts/probate-caveats-fe/values.aat.template.yaml
  config/default.yaml
  test/unit/testFeesLookup.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-316

#334 fixing the router journey
  app/healthcheck.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-334

#340 DTSPB1036-Welsh AccessbilityTests
  Jenkinsfile_nightly
  bin/run-nightly-functional-tests.sh
  package.json
  test/accessibility/a11yTest.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-340
