Repository hmcts/probate-caveats-frontend, pull requests merged in 2021-02, with the labels that each got.

#353 DTSPB-1210: change the operating hours
  app/resources/cy/translation/common.json
  app/resources/en/translation/common.json
  config/testing.yaml
  test/end-to-end/config.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-353

#319 adding avaya webchat
  app.js
  app/assets/images/icon.png
  app/assets/javascripts/avaya-webchat.js
  app/assets/locales/avaya-webchat/locale_en-GB.json
  app/assets/sass/application-ie8.scss
  app/assets/sass/application.scss
  app/assets/sass/patterns/_avaya-webchat.scss
  app/core/steps/Step.js
  app/featureToggles.js
  app/resources/cy/translation/static/avaya-webchat.json
  app/resources/en/translation/static/avaya-webchat.json
  app/steps/ui/static/avaya-webchat/index.js
  app/steps/ui/static/avaya-webchat/template.html
  app/views/includes/avaya-webchat.html
  app/views/includes/head.html
  app/views/includes/help_details.html
  app/views/includes/scripts.html
  config/default.yaml
  config/dev.yaml
  test/component/static/testAvayaWebchat.js
  test/util/TestWrapper.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-319

#356 Caveat to use new keyword without feature toggle
  app/utils/FeesLookup.js
  test/unit/testFeesLookup.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-356

#363 DTSPB-1389: adding logging to check why keyword failed in AAT
  app/utils/FeesLookup.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-363

#341 Ta 187 payments consumer tests
  Jenkinsfile_CNP
  config/default.yaml
  package.json
  test/contract/pact/cer/ca-bundle.crt
  test/contract/pact/external/FeesRegisterClient.spec.js
  test/contract/pact/external/PaymentClient.spec.js
  test/contract/publish/PublishPacts.js
  test/end-to-end/config.js
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-341

#364 adding /health/readiness
  .github/renovate.json
  app.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-364

#355 DTPSB-1264: adding Webchat details into the contact us page
  app/steps/ui/static/contact/template.html
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-355

#367 Dtspb 1448 update library
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-367

#354 DTSPB-1263: update privacy policy additions
  app/resources/cy/translation/static/privacy.json
  app/resources/en/translation/static/privacy.json
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-354
