Repository hmcts/probate-caveats-frontend, pull requests merged in 2021-11, with the labels that each got.

#425 DTSPB-2214: Remove deceased dob
  app/resources/cy/translation/deceased/dob.json
  app/resources/cy/translation/deceased/dobknown.json
  app/resources/en/translation/deceased/dob.json
  app/resources/en/translation/deceased/dobknown.json
  app/steps/ui/deceased/dob/index.js
  app/steps/ui/deceased/dob/schema.json
  app/steps/ui/deceased/dob/template.html
  test/component/deceased/testDoB.js
  test/unit/core/testDateStep.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-425

#429 DTSPB-2481 Fix dep failure
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-429

#430 DTSPB-2491 Update Volume Dep Version
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-430
