Repository hmcts/probate-caveats-frontend, pull requests merged in 2021-06, with the labels that each got.

#376 DTSPB-1670: ordnance survey new api
  README.md
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-376

#393 DTSPB-2020 Sync All branches to master with every build
  Jenkinsfile_CNP
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-393

#394 Dtspb 2027 exclude scripts from sonar
  app/views/includes/avaya-webchat.html
  app/views/includes/head.html
  app/views/includes/scripts.html
  package.json
  sonar-project.properties
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-394

#365 remove probate-newfee-register-code feature toggle as it's no longer …
  app/featureToggles.js
  app/middleware/lookupPaymentFees.js
  app/steps/ui/payment/breakdown/index.js
  app/utils/FeesLookup.js
  config/default.yaml
  test/unit/testFeesLookup.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-365
