Repository hmcts/probate-caveats-frontend, pull requests merged in 2021-09, with the labels that each got.

#417 DTSPB-2283: remove tunnelIdentifier
  test/end-to-end/saucelabs.conf.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-417

#401 DTSPB-2213: removing dob
  app/components/submit-data.js
  app/journeys/probate-caveats.js
  app/steps/ui/deceased/dobknown/index.js
  app/steps/ui/deceased/dobknown/schema.json
  app/steps/ui/deceased/dobknown/template.html
  app/steps/ui/summary/includes/deceased.njk
  test/component/deceased/testDoD.js
  test/component/deceased/testDoDKnown.js
  test/component/summary/testDeceasedSection.js
  test/data/deceased.json
  test/data/unit/fullcaveatform.json
  test/end-to-end/pages/deceased/dob.js
  test/end-to-end/pages/deceased/dobknown.js
  test/end-to-end/paths/caveat.e2e.js
  test/end-to-end/paths/caveatstopAndContinue.e2e.js
  test/unit/components/testSubmitData.js
  test/unit/testDeceasedDob.js
  test/unit/testDeceasedDobKnown.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-401

#420 Comment the IE Browser from caveats FE nightly
  test/crossbrowser/supportedBrowsers.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-420
