Repository hmcts/probate-caveats-frontend, pull requests merged in 2021-01, with the labels that each got.

#345 DTSPB-1159: Upgrade crossbrowser e2e dependencies and test framework.
  bin/run-crossbrowser-tests.sh
  commit-msg.sh
  package.json
  test/crossbrowser/supportedBrowsers.js
  test/end-to-end/helpers/SauceLabsReportingHelper.js
  test/end-to-end/saucelabs.conf.js
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-345

#343 DTSPB-1075: health check upgrade
  app.js
  app/healthcheck.js
  app/middleware/completeEqualityTask.js
  app/routes.js
  app/utils/Healthcheck.js
  app/utils/healthOptions.js
  charts/probate-caveats-fe/Chart.yaml
  charts/probate-caveats-fe/requirements.yaml
  charts/probate-caveats-fe/values.preview.template.yaml
  charts/probate-caveats-fe/values.yaml
  config/default.yaml
  package.json
  test/route/app/healthcheck.int.js
  test/smoke/healthcheck.js
  test/unit/testHealthcheck.js
  test/unit/utils/testHealthOptions.js
  test/unit/utils/testHealthcheck.js
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-343

#346 DTSPB-1161: Setup chrome crossbrowser tests in nightly pipeline
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests.sh
  bin/run-nightly-functional-tests.sh
  package.json
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/pages/applicant/address.js
  test/end-to-end/pages/applicant/email.js
  test/end-to-end/pages/applicant/name.js
  test/end-to-end/pages/bilingualgop/bilingualgop.js
  test/end-to-end/pages/deceased/address.js
  test/end-to-end/pages/deceased/alias.js
  test/end-to-end/pages/deceased/dob.js
  test/end-to-end/pages/deceased/dobknown.js
  test/end-to-end/pages/deceased/dod.js
  test/end-to-end/pages/deceased/name.js
  test/end-to-end/pages/deceased/othernames.js
  test/end-to-end/pages/payment/govukconfirmpayment.js
  test/end-to-end/pages/payment/govukpayment.js
  test/end-to-end/pages/payment/paymentbreakdown.js
  test/end-to-end/pages/startapply/startapply.js
  test/end-to-end/pages/startpage/eauality.js
  test/end-to-end/pages/summary/summary.js
  test/end-to-end/pages/thankyou/thankyou.js
  test/end-to-end/paths/caveat.e2e.js
  test/end-to-end/paths/caveatstopAndContinue.e2e.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-346

#348 DTSPB-1163: Enable Firefox, IE11, Edge and Safari crossbrowser tests in the nightly pipeline
  bin/run-crossbrowser-tests.sh
  test/crossbrowser/runCrossBrowserTestsOvernight.sh
  test/crossbrowser/supportedBrowsers.js
  test/end-to-end/codecept.conf.js
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/pages/applicant/address.js
  test/end-to-end/pages/deceased/address.js
  test/end-to-end/pages/startpage/eauality.js
  test/end-to-end/paths/caveat.e2e.js
  test/end-to-end/saucelabs.conf.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-348

#285 PRO-7583: updating privacy policy addresses and email
  app/resources/cy/translation/static/privacy.json
  app/resources/en/translation/static/privacy.json
  app/steps/ui/static/privacy/template.html
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-285
