Repository hmcts/probate-caveats-frontend, pull requests merged in 2022-02, with the labels that each got.

#439 DTSPB-2560: corrected contact hours
  app/resources/cy/translation/common.json
  app/resources/en/translation/common.json
  app/steps/ui/static/contact/template.html
  app/views/includes/help_details.html
  test/component/common/testCommonContent.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-439

#438 Dtspb 2395 avaya webchat testing
  app.js
  app/steps/ui/static/avaya-webchat/template.html
  app/views/includes/avaya-webchat.html
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-438

#444 DTSPB-2586 fix cves
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-444

#448 DTSPB-2596: Upgrade ajv
  app/steps/action/addAlias/schema.json
  app/steps/action/addressLookup/schema.json
  app/steps/action/removeAlias/schema.json
  app/steps/ui/applicant/address/schema.json
  app/steps/ui/applicant/email/schema.json
  app/steps/ui/applicant/name/schema.json
  app/steps/ui/deceased/address/schema.json
  app/steps/ui/deceased/alias/schema.json
  app/steps/ui/deceased/dod/schema.json
  app/steps/ui/deceased/name/schema.json
  app/steps/ui/deceased/othernames/schema.json
  app/steps/ui/equality/schema.json
  app/steps/ui/language/schema.json
  package.json
  test/unit/core/testAddressStep.js
  test/unit/testAddressStep.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-448

#449 add PCQ URL to staging conf for nightly values.aat.template.yaml
  charts/probate-caveats-fe/values.aat.template.yaml
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-449

#451 DTSPB-2617: upgraded nodejs chart
  charts/probate-caveats-fe/Chart.yaml
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-451
