Repository hmcts/probate-caveats-frontend, pull requests merged in 2022-08, with the labels that each got.

#464 Dtspb 1858 update pcq token algorithm
  app/middleware/completeEqualityTask.js
  app/steps/ui/equality/createToken.js
  charts/probate-caveats-fe/values.preview.template.yaml
  test/service-stubs/equalityAndDiversityHealth.js
  test/unit/testEquality.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-464

#541 dtspb-2942 ewt and text changes
  app/assets/javascripts/avaya-webchat-1.js
  app/assets/locales/avaya-webchat/locale_en-GB.json
  app/resources/cy/translation/common.json
  app/resources/en/translation/common.json
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-541

#545 DTSPB-2977 Revert EWT changes
  app/assets/javascripts/avaya-webchat-1.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-545

#547 DTSPB-2977 force update browsers
  app/assets/javascripts/avaya-webchat-3.js
  app/views/includes/scripts.html
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-547

#546 Add backstage configuration file
  catalog-info.yaml
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-546

#543 DTSPB-2848 healthOptions was written badly needed fix to work and upp…
  app.js
  app/utils/healthOptions.js
  app/utils/setupHealthCheck.js
  config/default.yaml
  sonar-project.properties
  test/unit/utils/testHealthOptions.js
  test/unit/utils/testSetupHealthCheck.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-543
