Repository hmcts/probate-caveats-frontend, pull requests merged in 2022-06, with the labels that each got.

#524 DTSPB-2846: fix liveness and cve
  test/component/testLiveness.js
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-524

#525 Update renovate so run weekly creates single PR
  .github/renovate.json
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-525

#523 DTSPB-2473: add logs to AI
  app.js
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-523

#528 DTSPB-2473: line with PFE changes
  app.js
  app/setupSecrets.js
  package.json
  server.js
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-528
