Repository hmcts/probate-caveats-frontend, pull requests merged in 2023-08, with the labels that each got.

#631 DTSPB-3726 Suppress CVE
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-631

#634 DTSPB-3739 Probate Caveats FE CVE Suppression
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-634

#633 update phone/webchat opening hours
  app/resources/en/translation/common.json
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-633
