Repository hmcts/probate-caveats-frontend, pull requests merged in 2023-03, with the labels that each got.

#587 DTSPB-3389 - Yarn v3
  .gitignore
  .nycrc.json
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  Jenkinsfile_CNP
  README.md
  config/test.yaml
  package.json
  sonar-project.properties
  test/accessibility/a11yTest.js
  test/end-to-end/helpers/GeneralHelpers.js
  test/end-to-end/paths/caveat.e2e.js
  test/end-to-end/paths/caveatstopAndContinue.e2e.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, rel:probate-caveats-fe-pr-587

#588 DTSPB-3408 - Edit renovate config
  .github/renovate.json
  Jenkinsfile_CNP
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-588

#595 DTSSE-2832 - Update terraform version
  infrastructure/.terraform-version
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:probate, prd:probate, add-or-update, rel:probate-caveats-fe-pr-595

#599 DTSPB-3458 - Upgrades to remove suppressions
  .eslintrc.js
  app.js
  app/utils/getContentSecurityPolicy.js
  config/testing.yaml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, rel:probate-caveats-fe-pr-599

#601 DTSPB-3481 Suppress CVE
  config/testing.yaml
  test/end-to-end/config.js
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, nightly, rel:probate-caveats-fe-pr-601

#603 DTSPB-3498 Fix CVE
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-603
