Repository hmcts/probate-caveats-frontend, pull requests merged in 2023-06, with the labels that each got.

#615 Updating renovate config
  .github/renovate.json
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-615

#616 DTSPB-3629 suppress CVE for FE & CVE
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-616

#620 DTSPB-3636 CVE suppression for Caveat Frontend
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-620

#617 DTSPB-3439 upgrade Redis from 4 to 6
  infrastructure/main.tf
Labels: ns:probate, prd:probate, nightly, destroy, rel:probate-caveats-fe-pr-617
