Repository hmcts/probate-caveats-frontend, pull requests merged in 2023-07, with the labels that each got.

#623 DTSPB-3659 CVE suppression for Caveat Frontend
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-623

#624 DTSPB-3588 update Exit survey Link
  app/assets/sass/application-ie8.scss
  app/assets/sass/application.scss
  app/resources/cy/translation/common.json
  app/resources/en/translation/common.json
  app/steps/ui/thankyou/template.html
  app/views/errors/error.html
  app/views/includes/layout.html
Labels: ns:probate, prd:probate, nightly, rel:probate-caveats-fe-pr-624

#629 DTSPB-3588 Update survey link changes
  app/resources/cy/translation/common.json
  app/resources/en/translation/common.json
  app/steps/ui/thankyou/template.html
  app/views/errors/error.html
  app/views/includes/layout.html
Labels: ns:probate, prd:probate, nightly, rel:probate-caveats-fe-pr-629
