Repository hmcts/probate-caveats-frontend, pull requests merged in 2023-09, with the labels that each got.

#635 DTSPB-3691 added walesh translation on exit survey link .
  app/resources/cy/translation/common.json
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-635, enable_keep_helm

#637 DTSPB-3760 update renovate config
  .github/renovate.json
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-637

#638 DTSPB-3807 Move away from using Docker.io to own ACR hmctspublic.azur…
  charts/probate-caveats-fe/values.preview.template.yaml
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-638
