Repository hmcts/probate-caveats-frontend, pull requests merged in 2023-10, with the labels that each got.

#647 Migrate redis cache to Basic sku in non-prod env
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:probate, prd:probate, destroy, rel:probate-caveats-fe-pr-647

#660 DTSPB-3839 cve
  .github/renovate.json
  Dockerfile
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-660

#666 DTSPB-3841 Fix CVE
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, nightly, rel:probate-caveats-fe-pr-666

#667 DTSPB-3842 added the security dynatrace
  app/utils/getContentSecurityPolicy.js
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-667
