Repository hmcts/probate-caveats-frontend, pull requests merged in 2025-02, with the labels that each got.

#1021 DTSPB-4099 govuk-frontend v5 upgrade
  README.md
  app.js
  app/assets/sass/application-ie8.scss
  app/assets/sass/application.scss
  app/views/includes/head.html
  app/views/includes/scripts.html
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, rel:probate-caveats-fe-pr-1021

#1095 DTSPB-4099 fix CSP and js error
  app/utils/getContentSecurityPolicy.js
  app/views/includes/scripts.html
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-1095

#1113 enable corepack, update yarn calls to work in v4.
  Dockerfile
Labels: ns:probate, prd:probate, rel:probate-caveats-fe-pr-1113
